name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          REPO_URI=${{ steps.login-ecr.outputs.registry }}/droneshield
          docker build -t $REPO_URI:${{ github.sha::8 }} .

      - name: Push Docker image
        run: |
          REPO_URI=${{ steps.login-ecr.outputs.registry }}/droneshield
          docker push $REPO_URI:${{ github.sha::8 }}
